-- Incident: moving only tables and forgetting sequences, default privileges, ownership, and dependent functions.
-- Repair goal: inventory dependencies first and verify grants after restore or schema move.
