-- Incident: choosing schema-per-tenant because it sounds isolated without planning migrations across hundreds of schemas.
-- Repair goal: write down tenant count, restore needs, migration fan-out, and reporting queries before choosing the pattern.
