from pgfound.llm import templates


def context_for(template_id: str) -> dict[str, object]:
    return {
        "allowed_concepts": ["select", "where", "primary_key", "index", "transaction"],
        "not_yet_allowed_concepts": ["window_function", "partitioning", "extension"],
        "concept_slug": "foreign_key",
        "lesson_context": "Foreign keys preserve references between tables.",
        "learner_level": "early",
        "learner_background": "backend engineer",
        "confusion_signal": "Learner thinks a join enforces relationship validity.",
        "learner_artifact": "select * from orders join customers using (customer_id);",
        "exercise_id": "first-select-write-query",
        "learner_sql": "select id from providers;",
        "reference_sql": "select id from providers;",
        "rubric_id": "query-correctness",
        "findings": [],
        "learner_schema": "create table customers (id bigint primary key);",
        "reference_schema": "create table customers (id bigint primary key);",
        "learner_index_plan": "create index on orders (customer_id);",
        "workload_description": "Lookup recent orders by customer.",
        "existing_schema": "create table orders (id bigint, customer_id bigint);",
        "query_examples": ["select * from orders where customer_id = 1;"],
        "scenario_id": "inventory-lost-update",
        "race_description": "Two sessions decrement the same row.",
        "proposed_fix": "select * from inventory where id = 1 for update;",
        "observed_trace": "both sessions read quantity 1",
        "reference_fix": "select ... for update",
        "learner_review_report": "# Review\nMissing invariant.",
        "learner_stage": "phase 3",
        "available_lessons": ["constraints-as-truth"],
        "available_exercises": ["first-select-write-query"],
        "exercise_level": "A",
        "exercise_prompt": "Write a simple SELECT.",
        "learner_attempt": "select * from providers;",
        "stuck_point": "I do not know which column to filter.",
        "common_mistake": "Using prose rules instead of constraints.",
        "domain_context": "Scheduling appointments.",
        "scenario_title": "Senior backend - multi-tenant SaaS with RLS",
        "duration_minutes": 45,
        "capability_layers_required": ["schema_literacy", "security_federation"],
        "stage_kind": "design_probe",
        "topic": "multi_tenant_rls",
        "previous_stages": [],
        "latest_response": "I would start with tenant invariants.",
        "full_transcript": "Learner defended tenant-scoped RLS.",
        "stage_transcript": "Prompt and learner response.",
        "capstone_id": "01-multi-tenant-saas-crm",
        "capstone_metadata": {"id": "01-multi-tenant-saas-crm"},
        "learner_artifacts": {
            "schema.sql": "create table accounts (id bigint primary key);",
            "indexes.sql": "create index on accounts (id);",
            "rls-policies.sql": "alter table accounts enable row level security;",
            "critical-queries.sql": "select 1;",
            "operational-runbook.md": "Rollback and monitor.",
            "writeup.md": "Extension posture: not yet.",
        },
        "reference_artifacts": {
            "schema.sql": "create table accounts (id bigint primary key);",
            "indexes.sql": "create index on accounts (id);",
            "rls-policies.sql": "alter table accounts enable row level security;",
            "critical-queries.sql": "select 1;",
            "operational-runbook.md": "Rollback and monitor.",
            "writeup.md": "Extension posture: not yet.",
        },
        "engine_result": {"overall_score": 1.0},
        "rubric": {"id": "capstone"},
    }


def test_each_template_has_a_complete_integration_context() -> None:
    for template in templates.list_templates():
        context = templates.merge_context(template, context_for(template.id))
        templates.validate_inputs(template, context)
