-- Incident: reviewing only application documentation and never comparing it to catalog evidence.
-- Repair goal: attach catalog query output to a recurring access review and diff it after deployments.
