-- Unsafe state: running default privileges after an outage and assuming old tables changed too.
-- Expected remediation: pair default privileges with explicit `GRANT ... ON ALL ... IN SCHEMA` for existing objects.
