-- Incident: using the migration owner as the application runtime role because it makes deployments convenient.
-- Repair goal: write the role matrix first, then make every GRANT trace back to one cell in that matrix.
