-- Migrating Between Schemas and Databases Level D1
-- Unsafe state: moving only tables and forgetting sequences, default privileges, ownership, and dependent functions.
-- Remediation: inventory dependencies first and verify grants after restore or schema move.
-- Use targeted REVOKE or ALTER statements instead of broad superuser access.
